---
- name: Clone Dryad repo
  git: repo={{ dryad.repo }}
       dest={{ dryad.repo_path }}
  sudo: no

- name: Make m2 directory
  file: path=/home/vagrant/.m2 state=directory owner=vagrant mode=0755

- name: Copy settings.xml for maven profile
  template: src=settings.xml.j2 dest="/home/vagrant/.m2/settings.xml"
  sudo: no

- name: Make private tomcat instance
  command: tomcat6-instance-create {{ dryad.tomcat_home }} creates={{ dryad.tomcat_home }}
  sudo: no

- name: Update tomcat server.xml
  template: src=server.xml.j2 dest={{ dryad.tomcat_home }}/conf/server.xml backup=yes
  sudo: no

- name: Update setenv.sh JDK_DIRS
  lineinfile: dest={{ dryad.tomcat_home }}/bin/setenv.sh regexp='^JDK_DIRS=' line='JDK_DIRS="/usr/lib/jvm/java-6-oracle"'

- name: Update setenv.sh JAVA_OPTS
  lineinfile: dest={{ dryad.tomcat_home }}/bin/setenv.sh regexp=^'\s+JAVA_OPTS=' line='    JAVA_OPTS="-Xmx4096m -XX:+CMSClassUnloadingEnabled -XX:PermSize=512M -XX:MaxPermSize=512M"'

- name: Make global startup-debug.sh script
  command: cp /usr/share/tomcat6/bin/startup.sh /usr/share/tomcat6/bin/startup-debug.sh creates=/usr/share/tomcat6/bin/startup-debug.sh

- name: Update global startup-debug.sh script
  lineinfile: dest=/usr/share/tomcat6/bin/startup-debug.sh regexp='^exec ' line='exec "$PRGDIR"/"$EXECUTABLE" jpda start "$@"'

- name: Make dryad startup-debug.sh script
  shell: cp {{ dryad.tomcat_home }}/bin/startup.sh {{ dryad.tomcat_home }}/bin/startup-debug.sh creates={{ dryad.tomcat_home }}/bin/startup-debug.sh
  sudo: no

- name: Update startup-debug.sh script
  lineinfile: dest={{ dryad.tomcat_home }}/bin/startup-debug.sh regexp='/usr/share/tomcat6/bin/startup' line='/usr/share/tomcat6/bin/startup-debug.sh'

- name: Make bin directory
  file: path=/home/vagrant/bin state=directory owner=vagrant mode=0755
  sudo: no

- name: install bash profile to update path
  copy: src=.bash_profile dest="/home/vagrant/.bash_profile" mode=0644
  sudo: no

- name: Install build script
  template: src=build_dryad.sh.j2 dest="/home/vagrant/bin/build_dryad.sh" mode=0755
  sudo: no

- name: Install deploy script
  template: src=deploy_dryad.sh.j2 dest="/home/vagrant/bin/deploy_dryad.sh" mode=0755
  sudo: no

- name: Install build indexes script
  template: src=build_indexes.sh.j2 dest="/home/vagrant/bin/build_indexes.sh" mode=0755
  sudo: no

- name: Install database script
  template: src=install_dryad_database.sh.j2 dest="/home/vagrant/bin/install_dryad_database.sh" mode=0755

- name: Copy carrot2-mini-3.1.0.jar for installation
  copy: src=carrot2-mini-3.1.0.jar dest=/tmp/

- name: Copy script to install missing poms
  copy: src=install_missing_poms.sh dest=/home/vagrant/bin/install_missing_poms.sh mode=0755
  sudo: no

- name: Install missing poms
  command: /home/vagrant/bin/install_missing_poms.sh chdir={{ dryad.repo_path }}/dspace/etc/discoverySnapshot
  sudo: no

- name: Make install directory
  file: path={{ dryad.install_dir }} state=directory owner=vagrant mode=0755

- name: Make log directory
  file: path={{ dryad.install_dir }}/log state=directory owner=vagrant mode=0755

- name: Place motd file
  template: src=motd.tail.j2 dest=/etc/motd.tail mode=0644 owner=root

- name: Regenerated motd for next login
  shell: run-parts /etc/update-motd.d/ > /var/run/motd
