---
- name: Install Dryad dependencies
  apt: pkg={{ item }} state=installed update-cache=yes
#  async: 60
#  poll: 60
  with_items:
    - openjdk-8-jdk
    - git
    - maven
    - ant
    - perl
    - tomcat8
    - tomcat8-user
    - python-psycopg2
    - screen
    - xvfb
    - firefox
  tags:
    - packages
