---
- name: Install Dryad dependencies
  apt: pkg={{ item }} state=installed update-cache=yes
  async: 60
  poll: 60
  with_items:
    - oracle-java6-installer
    - git
    - maven2
    - ant
    - perl
    - tomcat6
    - tomcat6-user
    - python-psycopg2
    - screen
    - xvfb
    - firefox
  tags:
    - packages
